# version: '3.8'

# services:
#   app:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     ports:
#       - "5000:5000"
#     environment:
#       - NODE_ENV=production
#     volumes:
#       - .:/app
#     networks:
#       - app-network

# networks:
#   app-network:
#     driver: bridge

services:
  backend:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - src/.env
    depends_on:
      - frontend
      
  frontend:
    build: ./my-project
    ports:
      - "5000:5000"
    environment:
      - API_URL=https://sbd-finpro-kuliah.vercel.app/api